### PR TITLE
Remove outdated man script, add compilation and setup instructions

### PR DESCRIPTION
**Pull request by dfaure-kdab**

### CODE REVIEW

**Comment by dfaure-kdab** [comment]
ping?

**Comment by mbornet-hl** [comment]
pong !

**Comment by dfaure-kdab** [comment]
Hi ;) any chance of getting this commit merged?

**Comment by mbornet-hl** [comment]
Hello David,

yes, I'll work again on "hl" soon, and I'll also add an interesting 
functionnality, if I can manage to implement it.
Sorry for the delay, I've been working on other projects.

Regards,

Martial Bornet

tel  : 06 13 33 52 77
site : http://www.bornet.fr/

**Comment by mbornet-hl** [comment]
Things have been cleaned and documented.

**Comment by dfaure-kdab** [comment]
scripts/hl_man_pager still hardcodes /usr/local/bin/hl which is incorrect if hl isn't installed there.

**Comment by mbornet-hl** [comment]
I removed the dirname from the hl pathname, so it should work if hl is 
accessible via the PATH.

Martial Bornet

**Pull request closed without merging**
